### ISSUE TITLE
No module named 'textblob.translate'

### ISSUE THREAD

**Issue by CMC-whut** [shiningrain/JailGuard#1]
The latest version of Textblob has following change:

TextBlob.translate() and TextBlob.detect_language are deprecated. Use the official Google Translate API instead
Hence the import is failing while using textaugment. Please fix this. My Production environment depends on this.

https://textblob.readthedocs.io/en/latest/changelog.html

**Comment by shiningrain** [comment]
Thank you for your kindly reminder. We are using Textblob version 0.17.1, which was released in 2021 and it still works. I find that th PyPI page of this project has just released 0.18ver this year.
Considering the risk of these APIs being deprecated, we will actively update the implementation of the mutators in the future.
